import 'server-only';
import { v1 as documentai } from '@google-cloud/documentai';
import type { protos } from '@google-cloud/documentai';
import type { MedicalReport } from '@/features/reports/types';
import type { BoundingBox, OcrLayout, OcrPage, OcrTable } from '@/features/extraction/types';
type Document = protos.google.cloud.documentai.v1.IDocument;
const client = new documentai.DocumentProcessorServiceClient();
const textAt = (document: Document, anchor: protos.google.cloud.documentai.v1.Document.ITextAnchor | null | undefined) => { if (!anchor?.textSegments?.length || !document.text) return ''; return anchor.textSegments.map(segment => document.text?.slice(Number(segment.startIndex ?? 0), Number(segment.endIndex ?? 0)) ?? '').join(''); };
function box(vertices: protos.google.cloud.documentai.v1.IVertex[] | null | undefined): BoundingBox | undefined { if (!vertices?.length) return undefined; const xs = vertices.map(v => Number(v.x ?? 0)); const ys = vertices.map(v => Number(v.y ?? 0)); return { x: Math.min(...xs), y: Math.min(...ys), width: Math.max(...xs) - Math.min(...xs), height: Math.max(...ys) - Math.min(...ys) }; }
function pageNo(value: number | null | undefined, fallback: number) { return Number.isFinite(Number(value)) && Number(value) > 0 ? Number(value) : fallback; }
function tables(document: Document, page: protos.google.cloud.documentai.v1.Document.IPage, number: number): OcrTable[] { return (page.tables ?? []).map((table: protos.google.cloud.documentai.v1.Document.Page.ITable) => ({ pageNumber: number, rows: [...(table.headerRows ?? []), ...(table.bodyRows ?? [])].map(row => (row.cells ?? []).map(cell => textAt(document, cell.layout?.textAnchor))), boundingBox: box(table.layout?.boundingPoly?.normalizedVertices?.length ? table.layout?.boundingPoly?.normalizedVertices : table.layout?.boundingPoly?.vertices) })); }
export function normalizeDocument(document: Document, processedAt = new Date().toISOString()): OcrLayout { const pages: OcrPage[] = (document.pages ?? []).map((page, index) => { const number = pageNo(page.pageNumber, index + 1); return { pageNumber: number, text: (page.paragraphs ?? []).map(paragraph => textAt(document, paragraph.layout?.textAnchor)).join('\n'), width: Number(page.dimension?.width ?? 0) || undefined, height: Number(page.dimension?.height ?? 0) || undefined }; }); return { text: document.text ?? pages.map(page => page.text).join('\n'), pages, tables: (document.pages ?? []).flatMap((page, index) => tables(document, page, pageNo(page.pageNumber, index + 1))), processedAt, extractionMethod: 'GOOGLE_DOCUMENT_AI' }; }
export function documentAiConfigured() { return Boolean(process.env.DOCUMENT_AI_PROJECT_ID && process.env.DOCUMENT_AI_LOCATION && process.env.DOCUMENT_AI_PROCESSOR_ID); }
export function processorName() { const project = process.env.DOCUMENT_AI_PROJECT_ID; const location = process.env.DOCUMENT_AI_LOCATION; const processor = process.env.DOCUMENT_AI_PROCESSOR_ID; if (!project || !location || !processor) throw new Error('Document AI processor is not configured'); return `projects/${project}/locations/${location}/processors/${processor}`; }
export async function processWithGoogleDocumentAi(bytes: Buffer, report: MedicalReport): Promise<OcrLayout> { const [response] = await client.processDocument({ name: processorName(), rawDocument: { content: bytes, mimeType: report.mimeType } }, { timeout: 90000 }); if (!response.document) throw new Error('Document AI returned no document'); return normalizeDocument(response.document); }
