"use client";
import { useMemo, useState } from 'react';
import type { PatientProfile } from '@/lib/types';
import { recordCompleteness } from './conflict-engine';
export function IntelligenceOverview({ patient }: { patient: PatientProfile | null }) {
  const [active, setActive] = useState('overview');
  const signals = useMemo(() => recordCompleteness({ profile: Boolean(patient), reports: 0, verifiedReports: 0, medications: patient?.medications ? 1 : 0, allergies: patient?.allergies ? 1 : 0, conditions: patient?.conditions ? 1 : 0 }), [patient]);
  const complete = signals.filter(signal => signal.present).length;
  return <section aria-labelledby="intelligence-heading" className="depth-panel rounded-3xl p-6 md:p-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Trust dashboard</p><h2 id="intelligence-heading" className="mt-2 text-2xl font-bold">Your record at a glance</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">A guided view of what is present, what needs review, and where each fact came from.</p></div><div className="score-orb" aria-label={`${complete} of ${signals.length} record areas present`}><span>{complete}/{signals.length}</span><small>ready</small></div></div><div className="mt-6 flex flex-wrap gap-2" role="tablist" aria-label="Record overview sections">{[['overview', 'Completeness'], ['trust', 'Trust labels'], ['next', 'Next steps']].map(([key, label]) => <button key={key} role="tab" aria-selected={active === key} onClick={() => setActive(key)} className={`rounded-full px-4 py-2 text-sm font-bold transition ${active === key ? 'bg-ink text-white' : 'bg-white text-slate-600 hover:bg-teal/10'}`}>{label}</button>)}</div>{active === 'overview' && <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{signals.map(signal => <article key={signal.key} className="lift-card rounded-2xl border border-white/80 bg-white/80 p-4"><div className="flex items-center justify-between gap-3"><h3 className="font-bold">{signal.label}</h3><span className={`status-dot ${signal.present ? 'status-good' : 'status-warn'}`} aria-label={signal.present ? 'Present' : 'Needs attention'}>{signal.present ? 'Ready' : 'Open'}</span></div><p className="mt-2 text-sm text-slate-600">{signal.present ? 'Available for review.' : signal.action}</p></article>)}</div>}{active === 'trust' && <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{['Patient provided', 'Extracted from report', 'Needs verification', 'View evidence'].map(label => <div key={label} className="lift-card rounded-2xl border border-white/80 bg-white/80 p-4"><span className="text-xs font-bold uppercase tracking-wider text-teal">Trust label</span><p className="mt-2 font-bold">{label}</p></div>)}</div>}{active === 'next' && <div className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-5"><h3 className="font-bold text-amber-950">Review-first workflow</h3><p className="mt-2 text-sm leading-6 text-amber-950">Upload a source report, inspect its extracted evidence, and verify facts before they become part of your trusted record. MedLens does not diagnose or recommend treatment.</p></div>}</section>;
}
