import { randomUUID } from 'node:crypto';
import type { MedicalReport } from '@/features/reports/types';
import type { OcrLayout, Confidence, ReportType, SourceEvidence } from './types';
import { extractedDraftSchema, type ValidatedDraft } from './schemas';
import { classifyText, type ClassificationResult } from './classification';
export interface DocumentAiProvider { process(bytes: Buffer, mimeType: MedicalReport['mimeType']): Promise<OcrLayout>; }
export function draftFromOcr(report: MedicalReport, ocr: OcrLayout): ValidatedDraft { const classification = classifyText(ocr.text); const now = new Date().toISOString(); const draft = { extractionId: randomUUID(), reportId: report.reportId, patientId: report.patientId, ownerId: report.ownerId, reportType: classification.type, reportTypeConfidence: classification.confidence, observations: parseLabLines(report.reportId, ocr, now), medications: parseMedicationLines(report.reportId, ocr, now), conditions: [], symptoms: [], notes: [], ocr, status: 'DRAFT' as const, createdAt: now, updatedAt: now }; return extractedDraftSchema.parse(draft); }
function sourceEvidence(reportId: string, pageNumber: number, sourceText: string, confidence: Confidence, createdAt: string): SourceEvidence { return { reportId, pageNumber, sourceText, extractionMethod: 'GOOGLE_DOCUMENT_AI', confidence, createdAt }; }
function parseLabLines(reportId: string, ocr: OcrLayout, now: string): ValidatedDraft['observations'] { const results: ValidatedDraft['observations'] = []; for (const page of ocr.pages) for (const raw of page.text.split(/\r?\n/)) { const line = raw.trim().replace(/\s+/g, ' '); const match = line.match(/^(.{2,80}?)\s+(-?\d+(?:\.\d+)?)\s*([a-zA-Zµ/%][a-zA-Z0-9µ/%^.-]*)?(?:\s+((?:\d+(?:\.\d+)?\s*(?:-|–|to)\s*\d+(?:\.\d+)?|[<>≤≥]\s*\d+(?:\.\d+)?).*))?$/); if (!match || /^(page|date|patient|report|specimen)\b/i.test(match[1])) continue; const confidence: Confidence = match[4] ? 'MODERATE' : 'LOW'; results.push({ id: randomUUID(), testName: match[1].trim(), textualValue: match[2], numericValue: Number(match[2]), unit: match[3], referenceRangeText: match[4]?.trim(), confidence, provenance: sourceEvidence(reportId, page.pageNumber, line, confidence, now) }); } return results.slice(0, 5000); }
function parseMedicationLines(reportId: string, ocr: OcrLayout, now: string): ValidatedDraft['medications'] { const results: ValidatedDraft['medications'] = []; for (const page of ocr.pages) for (const raw of page.text.split(/\r?\n/)) { const line = raw.trim().replace(/\s+/g, ' '); const match = line.match(/^(?:\d+[.)]\s*)?([A-Za-z][A-Za-z0-9 -]{2,60})(?:\s+(\d+(?:\.\d+)?\s*(?:mg|mcg|g|ml|%)))?\s*(?:[-–:]\s*(.+))?$/i); if (!match || !/(tablet|capsule|syrup|mg|mcg|take|daily|bid|tid|od|medicine|medication)/i.test(line)) continue; results.push({ id: randomUUID(), medication: match[1].trim(), strength: match[2]?.trim(), frequency: match[3]?.trim(), confidence: 'LOW', provenance: sourceEvidence(reportId, page.pageNumber, line, 'LOW', now) }); } return results.slice(0, 500); }
export type { ClassificationResult };
