import { z } from 'zod';
import { REPORT_TYPES } from './types';
const box = z.object({ x: z.number().finite().min(0), y: z.number().finite().min(0), width: z.number().finite().min(0), height: z.number().finite().min(0) }).optional();
const evidence = z.object({ reportId: z.string().min(1), pageNumber: z.number().int().positive().optional(), sourceText: z.string().max(10000), boundingBox: box, extractionMethod: z.literal('GOOGLE_DOCUMENT_AI'), confidence: z.enum(['HIGH', 'MODERATE', 'LOW', 'NEEDS_REVIEW']), createdAt: z.string().datetime() });
const lab = z.object({ id: z.string().min(1), testName: z.string().min(1).max(200), textualValue: z.string().max(500), numericValue: z.number().finite().optional(), unit: z.string().max(80).optional(), referenceRangeText: z.string().max(200).optional(), confidence: z.enum(['HIGH', 'MODERATE', 'LOW', 'NEEDS_REVIEW']), provenance: evidence });
const medication = z.object({ id: z.string().min(1), medication: z.string().min(1).max(200), strength: z.string().max(100).optional(), frequency: z.string().max(100).optional(), confidence: z.enum(['HIGH', 'MODERATE', 'LOW', 'NEEDS_REVIEW']), provenance: evidence });
const ocr = z.object({ text: z.string().max(2_000_000), pages: z.array(z.object({ pageNumber: z.number().int().positive(), text: z.string().max(500_000), width: z.number().finite().optional(), height: z.number().finite().optional() })).max(200), tables: z.array(z.object({ pageNumber: z.number().int().positive(), rows: z.array(z.array(z.string().max(1000)).max(100)).max(1000), boundingBox: box })).max(500), processedAt: z.string().datetime(), extractionMethod: z.literal('GOOGLE_DOCUMENT_AI') });
export const extractedDraftSchema = z.object({ extractionId: z.string().min(1), reportId: z.string().min(1), patientId: z.string().min(1), ownerId: z.string().min(1), reportType: z.enum(REPORT_TYPES), reportTypeConfidence: z.enum(['HIGH', 'MODERATE', 'LOW', 'NEEDS_REVIEW']), reportDate: z.string().optional(), laboratoryName: z.string().max(300).optional(), observations: z.array(lab).max(5000), medications: z.array(medication).max(500), conditions: z.array(z.string().max(300)).max(200), symptoms: z.array(z.string().max(300)).max(200), notes: z.array(z.string().max(2000)).max(200), ocr, status: z.enum(['DRAFT', 'FAILED']), createdAt: z.string().datetime(), updatedAt: z.string().datetime() });
export type ValidatedDraft = z.infer<typeof extractedDraftSchema>;
